version: '3.8'

services:
  backend:
    build: ./backend/auth-service
    container_name: auth_service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/auth-service:/app

  frontend:
    build: ./webui
    container_name: web_ui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
